Because broadcasting allows for shorthand operations that make vector math efficient and possible, incorrect implementations will not throw errors.

In [ ]:
import numpy as np

a = np.random.randn(5)

[-0.3670817   0.94171713 -1.49564566 -0.41308129 -0.21660882]


In [3]:
print(a)

[-0.3670817   0.94171713 -1.49564566 -0.41308129 -0.21660882]


In [4]:
print(a.shape)

(5,)


(5,) <- this comma means it is called a "rank 1 array" which is neither a row vector or a column vector 

In [6]:
print(a.T)
print(a.T.shape)

[-0.3670817   0.94171713 -1.49564566 -0.41308129 -0.21660882]
(5,)


The shape is the same when you transpose.

In [7]:
print(np.dot(a,a.T))

3.4760915768174923


This returns a scalar instead of a matrix.  We should try to avoid rank 1 arrays by doing this

In [8]:
a = np.random.randn(5,1)
print(a)

[[ 0.67171292]
 [-1.20424291]
 [-0.26432677]
 [ 0.92846226]
 [-1.07678707]]


In [9]:
print(a.T)

[[ 0.67171292 -1.20424291 -0.26432677  0.92846226 -1.07678707]]


Notice the double square bracket ^^^ this means its a vector rather than this "rank 1 array"

In [10]:
print(np.dot(a, a.T))

[[ 0.45119825 -0.80890553 -0.17755171  0.6236601  -0.72329179]
 [-0.80890553  1.45020099  0.31831364 -1.11809409  1.29671319]
 [-0.17755171  0.31831364  0.06986864 -0.24541743  0.28462365]
 [ 0.6236601  -1.11809409 -0.24541743  0.86204216 -0.99975615]
 [-0.72329179  1.29671319  0.28462365 -0.99975615  1.15947039]]


We should always declare the full shape of vectors.  One dimension should always be 1 in vectors.  If you do end up with a rank 1 array, you can redefine the shape as follows

In [ ]:
a = a.reshape(5,1)